import {
  SiAngular,
  SiReact,
  SiDocker,
  SiTailwindcss,
  SiGit,
  SiGithub,
  SiNodedotjs,
  SiTypescript,
  SiJavascript,
  SiStryker,
  SiJasmine,
} from "react-icons/si";
import { VscTerminalLinux, VscAzure } from "react-icons/vsc";
import { TbBrandCSharp } from "react-icons/tb";
import { FaSass } from "react-icons/fa";
import { BiLogoVisualStudio } from "react-icons/bi";
import {
  DiVisualstudio,
  DiMsqlServer,
  DiSqllite,
  DiUbuntu,
  DiDotnet,
} from "react-icons/di";
import { TechnologiesInterface } from "@/interfaces/general/technologies";

/** Constante com as tecnologias utilizadas com ícones, nomes e cores */
export const AboutTechnologies: TechnologiesInterface[] = [
  {
    name: "Angular",
    icon: SiAngular,
    iconColor: "text-red-700 text-4xl",
    shadowColor: "from-red-700/10",
    glowColor: "from-red-700/50",
    tooltipColor: "bg-red-700",
    baseTooltipColor: "before:bg-red-700",
  },
  {
    name: "React",
    icon: SiReact,
    iconColor: "text-sky-500 text-4xl",
    shadowColor: "from-sky-500/10",
    glowColor: "from-sky-500/50",
    tooltipColor: "bg-sky-500",
    baseTooltipColor: "before:bg-sky-500",
  },
  {
    name: "TypeScript",
    icon: SiTypescript,
    iconColor: "text-blue-600 text-4xl",

    shadowColor: "from-blue-600/10",
    glowColor: "from-blue-600/50",
    tooltipColor: "bg-blue-600",
    baseTooltipColor: "before:bg-blue-600",
  },
  {
    name: "JavaScript",
    icon: SiJavascript,
    iconColor: "text-yellow-500 text-4xl",

    shadowColor: "from-yellow-500/10",
    glowColor: "from-yellow-500/50",
    tooltipColor: "bg-yellow-500",
    baseTooltipColor: "before:bg-yellow-500",
  },
  {
    name: "Node.js",
    icon: SiNodedotjs,
    iconColor: "text-lime-600 text-4xl",
    shadowColor: "from-lime-600/10",
    glowColor: "from-lime-600/50",
    tooltipColor: "bg-lime-600",
    baseTooltipColor: "before:bg-lime-600",
  },
  {
    name: "Stryker JS",
    icon: SiStryker,
    iconColor: "text-orange-700 text-4xl",
    shadowColor: "from-orange-700/10",
    glowColor: "from-orange-700/50",
    tooltipColor: "bg-orange-700",
    baseTooltipColor: "before:bg-orange-700",
  },
  {
    name: "Jasmine + Karma",
    icon: SiJasmine,
    iconColor: "text-fuchsia-400 text-4xl",
    shadowColor: "from-fuchsia-400/10",
    glowColor: "from-fuchsia-400/50",
    tooltipColor: "bg-fuchsia-400",
    baseTooltipColor: "before:bg-fuchsia-400",
  },
  {
    name: "Tailwind CSS",
    icon: SiTailwindcss,
    iconColor: "text-sky-500 text-4xl",
    shadowColor: "from-sky-500/10",
    glowColor: "from-sky-500/50",
    tooltipColor: "bg-sky-500",
    baseTooltipColor: "before:bg-sky-500",
  },
  {
    name: "SCSS",
    icon: FaSass,
    iconColor: "text-pink-500 text-4xl",
    shadowColor: "from-pink-500/10",
    glowColor: "from-pink-500/50",
    tooltipColor: "bg-pink-500",
    baseTooltipColor: "before:bg-pink-500",
  },
  {
    name: "C#",
    icon: TbBrandCSharp,
    iconColor: "text-purple-500 text-4xl",
    shadowColor: "from-purple-500/10",
    glowColor: "from-purple-500/50",
    tooltipColor: "bg-purple-500",
    baseTooltipColor: "before:bg-purple-500",
  },
  {
    name: "ASP.NET",
    icon: DiDotnet,
    iconColor: "text-blue-500 text-4xl",
    shadowColor: "from-blue-500/10",
    glowColor: "from-blue-500/50",
    tooltipColor: "bg-blue-500",
    baseTooltipColor: "before:bg-blue-500",
  },
  {
    name: "SQL Server",
    icon: DiMsqlServer,
    iconColor: "text-red-500 text-4xl",
    shadowColor: "from-red-500/10",
    glowColor: "from-red-500/50",
    tooltipColor: "bg-red-500",
    baseTooltipColor: "before:bg-red-500",
  },
  {
    name: "SQL Lite",
    icon: DiSqllite,
    iconColor: "text-blue-700 text-4xl",
    shadowColor: "from-blue-700/10",
    glowColor: "from-blue-700/50",
    tooltipColor: "bg-blue-700",
    baseTooltipColor: "before:bg-blue-700",
  },
  {
    name: "Linux",
    icon: VscTerminalLinux,
    iconColor: "text-gray-800 dark:text-white text-4xl",
    shadowColor: "from-gray-500/20",
    glowColor: "from-gray-500/50",
    tooltipColor: "bg-gray-500",
    baseTooltipColor: "before:bg-gray-500",
  },
  {
    name: "Ubuntu",
    icon: DiUbuntu,
    iconColor: "text-orange-600 text-4xl",
    shadowColor: "from-orange-600/10",
    glowColor: "from-orange-600/50",
    tooltipColor: "bg-orange-600",
    baseTooltipColor: "before:bg-orange-600",
  },
  {
    name: "Git",
    icon: SiGit,
    iconColor: "text-orange-700 text-4xl",
    shadowColor: "from-orange-700/10",
    glowColor: "from-orange-700/50",
    tooltipColor: "bg-orange-700",
    baseTooltipColor: "before:bg-orange-700",
  },
  {
    name: "Visual Studio Code",
    icon: BiLogoVisualStudio,
    iconColor: "text-blue-500 text-4xl",
    shadowColor: "from-blue-500/10",
    glowColor: "from-blue-500/50",
    tooltipColor: "bg-blue-500",
    baseTooltipColor: "before:bg-blue-500",
  },
  {
    name: "Visual Studio",
    icon: DiVisualstudio,
    iconColor: "text-purple-500 text-4xl",
    shadowColor: "from-purple-500/10",
    glowColor: "from-purple-500/50",
    tooltipColor: "bg-purple-500",
    baseTooltipColor: "before:bg-purple-500",
  },
  {
    name: "GitHub",
    icon: SiGithub,
    iconColor: "text-gray-800 dark:text-white text-4xl",
    shadowColor: "from-gray-500/20",
    glowColor: "from-gray-500/50",
    tooltipColor: "bg-gray-500",
    baseTooltipColor: "before:bg-gray-500",
  },

  {
    name: "Docker",
    icon: SiDocker,
    iconColor: "text-sky-500 text-4xl",
    shadowColor: "from-sky-500/10",
    glowColor: "from-sky-500/50",
    tooltipColor: "bg-sky-500",
    baseTooltipColor: "before:bg-sky-500",
  },
  {
    name: "Azure",
    icon: VscAzure,
    iconColor: "text-blue-500 text-4xl",
    shadowColor: "from-blue-500/10",
    glowColor: "from-blue-500/50",
    tooltipColor: "bg-blue-500",
    baseTooltipColor: "before:bg-blue-500",
  },
];
